### ISSUE TITLE
grpc support with yab templates

### ISSUE THREAD

**Issue by DAddYE** [yarpc/yab#259]
Hi all!

I'm trying to convert this yab command:

```bash
yab users uber.core_services.customer_platform.customergateway.CustomerGateway/GetUser -r '{"criteria": {"uuid": "5157e305-0b00-43a9-b5f0-0fd19e5305e9"}, "fields_to_select": {"base_field_mask": {"paths": ["user_info.name.first_name", "user_info.name.last_name"]}}}' -p localhost:6729
```

to a yab/yaml file:

```yaml
service: users
peer: localhost:6729
method: uber.core_services.customer_platform.customergateway.CustomerGateway/GetUser
request:
  criteria:
    uuid: 5157e305-0b00-43a9-b5f0-0fd19e5305e9
  fields_to_select:
    base_field_mask:
      paths:
        - user_info.name.first_name
        - user_info.name.last_name
```

However, when I run it I get:

```
Failed while parsing input: could not reach reflection server: context deadline exceeded
```
